apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "helm.name" . }}
  name: {{ include "helm.name" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if not .Values.image.override }}
      imagePullSecrets:
            - name: {{ .Values.image.pullSecret | default "docker-pull-creds" }}
      {{- else }}
      imagePullSecrets:
      {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "helm.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.override}}
          image: "{{.Values.image.override}}"
          {{- else}}
          image: "{{.Values.image.registry | default "registry.teckdigital.de" }}/kube/{{ .Values.organization }}/{{ .Values.repository }}/{{ .Values.mode }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          {{- if .Values.image.override }}
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.draftMode }}
            - name: DRAFT_MODE
              value: "true"
            {{- end }}
            {{- if .Values.strapi.url }}
            - name: STRAPI_URL
              value: {{ .Values.strapi.url }}
            {{- end }}
            {{- if .Values.strapi.token.secretName }}
            - name: STRAPI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.strapi.token.secretName }}
                  key: {{ .Values.strapi.token.secretKey }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 2 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port | default 3000 }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.nginx.configmap.enabled }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- end }}
      {{- if .Values.nginx.configmap.enabled }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "helm.fullname" . }}-nginx-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
