{{- if .Values.nginx.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        # Enable gzip (optional but useful for html/js/css)
        gzip on;

        server {
            listen 3000;
            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ /index.html;

                # Enable sub_filter to rewrite <html>
                sub_filter_once off;
                sub_filter "<html" "<html class=\"$cookie_theme\"";

                # Ensure correct content types are filtered
                sub_filter_types text/html;
            }

            # Cache control for _astro assets
            location ~* /_astro/.*\.(js|css|mjs|html|json|webp|svg|png|jpg|jpeg|gif|woff2?)$ {
                add_header Cache-Control "public, max-age=2592000, immutable";
            }
        }
    }
{{- end }}
